{"uuid": "b180af4a-e30e-468b-85ab-ff3028bdacb1", "children": ["3fbef9b7-2061-445a-acc7-9039fd8c4d61", "07eb51ed-0a30-4e9c-95c3-56d46d09d51f", "f6b49251-d83a-4a84-b538-82912696676f", "6bec0ea6-c915-49e1-8b84-7bb714755d44", "54c2f7af-200f-4679-92e8-aadff6baea32"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.17.0.1', port=4444): Max retries exceeded with url: //wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f66ad41c8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/bender/work/ui_api_autotest/conftest.py\", line 51, in browser\n    browser = webdriver.Remote(\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 422, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 421, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 443, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 783, in urlopen\n    return self.urlopen(\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 783, in urlopen\n    return self.urlopen(\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 783, in urlopen\n    return self.urlopen(\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 755, in urlopen\n    retries = retries.increment(\n  File \"/home/bender/work/ui_api_autotest/venv/lib/python3.9/site-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1643054556832, "stop": 1643054571950}], "start": 1643054556832, "stop": 1643054572661}